FROM openjdk:17-slim AS build

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

RUN ./mvnw dependency:go-offline -B

COPY src ./src

RUN ./mvnw clean package -DskipTests

FROM openjdk:17-slim AS production

WORKDIR /app

COPY --from=build /app/target/*.jar /app/app.jar
RUN chmod 755 /app/app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
